### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by nilskp** [rentamob/WebRTC-Leak-Prevent#1]
Provide a whitelist for exceptions.

**Comment by rentamob** [comment]
Unfortunately it's not possible. At least it wouldn't work well if I implemented it.

chrome.privacy options apply to the browser as a whole, not on a tab-by-tab basis. So a selective whitelist isn't possible without disabling leak protection for the entire browser.

You may find [WebRTC Leak Prevent Toggle](https://github.com/rentamob/WebRTC-Leak-Prevent-Toggle) useful. It also works on a whole-browser level, and it currently only uses the WebRTCMultipleRoutesEnabled option - but it works.

**Comment by nilskp** [comment]
Well, that's too bad. I can't disable it wholesale, as I rely too much on Hangouts, in which case I'm apparently hosed. :-(

Thanks for clarifying.

**Comment by Zibri** [comment]
LOL! at the moment is possible because of a bug :D 
if you allow microphone or camer on one page then the ip will leak again :D
