### ISSUE TITLE
Is the Project's Development Stalled?

### ISSUE THREAD

**Issue by alifarazz** [rentamob/WebRTC-Leak-Prevent#10]
Is this repo still being maintained, considering the fact that the lastest release is from 2018?

**Comment by a8763506128977812212307169331690** [comment]
Hi @alifarazz. At this stage, maintenance has not been required. This is a very simple extension that is unlikely to require maintenance. If the extension ever does break (due to changes in Chrome, for example), the extension will be updated. Thanks.
