### ISSUE TITLE
Timezone override option

### ISSUE THREAD

**Issue by DasTestament** [rentamob/WebRTC-Leak-Prevent#2]
Hello,

It would be nice if subject will be implemented in your awesome Opera extension to prevent client's browser timezone leak.

Example: You're living in US and using an VPN-endpoint in Netherlands. It will be possible to detect country you're coming from because of endpoint IP location and your browser timezone mismatch.

**Comment by rentamob** [comment]
I don't think this is possible using a Chrome/ium extension. Websites find your system time using JavaScript (eg. by creating a [Date object](http://www.w3schools.com/jsref/jsref_obj_date.asp)).

This extension is just controlling privacy settings that already exist in Chrome.

Blocking JavaScript from getting the system time is something I don't immediately know how to do, and I doubt it's possible to do with JavaScript inside of sandboxed iFrames. It would also likely cause breakage on many websites.

A better solution is a script that you run before you connect to a VPN in a particular region that sets your time and date to that region.
