### ISSUE TITLE
easy on/off

### ISSUE THREAD

**Issue by pguth** [rentamob/WebRTC-Leak-Prevent#3]
There are situations in which this plugin breaks the WebRTC functionality. Eg. in the university prevalent `eduroam` network (tested with this: https://pguth.github.io/peermesh/). It would be good to indicate the state via the extensions icon and allow it to be switched on and off there.

**Comment by rentamob** [comment]
I've made a separate toggle extension that behaves this way. [WebRTC Leak Prevent Toggle](https://github.com/rentamob/WebRTC-Leak-Prevent-Toggle).

I don't currently intend on merging the two. But I may in the future if there's demand.

**Comment by pguth** [comment]
Ah, ok, thanks! 😄 Maybe point that out in the repo?
