### ISSUE TITLE
Start with pre-set option.

### ISSUE THREAD

**Issue by Snowlav** [rentamob/WebRTC-Leak-Prevent#4]
Hello,

Is there a way to have the default option be `disable_non_proxied_udp` ?
I'm using this extension with selenium and handling options for extensions can be a pit of a pain.

So I was wondering if I could edit the source to have default option set to `disable_non_proxied_udp` and zip it back up for use in Selenium.

Thanks in advance.

**Comment by rentamob** [comment]
Hi.

I don't know whether you're asking for permission to edit the source, or
you're asking for assistance in editing.

If you're only asking for permission, then I grant you permission.

Otherwise, it's a very simply change and I'm willing to assist if that's
what you're asking for.

**Comment by Snowlav** [comment]
Hello,

Thanks for your reply and permission :) I was asking for both.
I have experience with coding but it's my first time working with (chrome)
extensions.

Some quick guidelines should be enough to get me going.

Thanks again!

**Comment by rentamob** [comment]
Sorry for the delay. I had university work due, and this kind of cost lost in my inbox.

What you want to do is really simple. 

All you need it a background.js file with the following:

`chrome.privacy.network.webRTCIPHandlingPolicy.set({
    value: 'disable_non_proxied_udp'
});`

You'd then delete options.html, and change the manifest accordingly. 

If you're still unsure, you can fork my extension and I'll submit a pull request with the changes.

**Comment by Snowlav** [comment]
No problem, thanks for getting back to me :)

Those instructions are clear.
I'll get started.


Thanks again !
