### ISSUE TITLE
Why not set "default" by default ? 

### ISSUE THREAD

**Issue by rayzzed** [rentamob/WebRTC-Leak-Prevent#9]
https://github.com/aghorler/WebRTC-Leak-Prevent/blob/23e85425152622cc9e5ca570a6b6432dd383c67c/js/background.js#L14

See https://cs.chromium.org/chromium/src/content/public/common/webrtc_ip_handling_policy.h?g=0

default and default_public_interface_only seems different why choosing default_public_interface_only instead of default ?
Why default doesn't appear in options ?
Is disable_non_proxied_udp the safest ?

**Comment by a8763506128977812212307169331690** [comment]
Hi. `default` is the equivalent of having the extension disabled, so it's not included as an option.
